---
# tasks file for vector
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name: "{{ vector_url }}"
    state: present
  tags:
    - vector
- name: Vector | Template Config
  ansible.builtin.template:
    src: vector.j2
    dest: vector.yml
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  tags:
    - vector
- name: Vector | Create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/vector.service
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  tags:
    - vector
- name: Vector | Start Service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  tags:
    - vector